# Auto-generated embedding extraction functions
# Generated by 01_explore_nemotron_datasets.py


def extract_text_nvidia_nemotron_post_training_dataset_v1(example):
    """Extract embeddable text from nvidia/Nemotron-Post-Training-Dataset-v1"""
    # Conversational format - concatenate messages
    messages = example['messages']
    text_parts = []
    for msg in messages:
        role = msg.get('role', 'unknown')
        content = msg.get('content', '')
        text_parts.append(f'{role}: {content}')
    return '\n'.join(text_parts)


def extract_text_nvidia_nemotron_post_training_dataset_v2(example):
    """Extract embeddable text from nvidia/Nemotron-Post-Training-Dataset-v2"""
    # Conversational format - concatenate messages
    messages = example['messages']
    text_parts = []
    for msg in messages:
        role = msg.get('role', 'unknown')
        content = msg.get('content', '')
        text_parts.append(f'{role}: {content}')
    return '\n'.join(text_parts)


def extract_text_nvidia_llama_nemotron_post_training_dataset(example):
    """Extract embeddable text from nvidia/Llama-Nemotron-Post-Training-Dataset"""
    # Conversational format - concatenate messages
    messages = example['messages']
    text_parts = []
    for msg in messages:
        role = msg.get('role', 'unknown')
        content = msg.get('content', '')
        text_parts.append(f'{role}: {content}')
    return '\n'.join(text_parts)


def extract_text_nvidia_nemotron_science_v1(example):
    """Extract embeddable text from nvidia/Nemotron-Science-v1"""
    # Conversational format - concatenate messages
    messages = example['messages']
    text_parts = []
    for msg in messages:
        role = msg.get('role', 'unknown')
        content = msg.get('content', '')
        # Include reasoning_content if available
        if 'reasoning_content' in msg and msg['reasoning_content']:
            content = msg['reasoning_content'] + '\n' + content
        text_parts.append(f'{role}: {content}')
    return '\n'.join(text_parts)


def extract_text_nvidia_nemotron_instruction_following_chat_v1(example):
    """Extract embeddable text from nvidia/Nemotron-Instruction-Following-Chat-v1"""
    # Conversational format - concatenate messages
    messages = example['messages']
    text_parts = []
    for msg in messages:
        role = msg.get('role', 'unknown')
        content = msg.get('content', '')
        # Include reasoning_content if available
        if 'reasoning_content' in msg and msg['reasoning_content']:
            content = msg['reasoning_content'] + '\n' + content
        text_parts.append(f'{role}: {content}')
    return '\n'.join(text_parts)


def extract_text_nvidia_nemotron_math_proofs_v1(example):
    """Extract embeddable text from nvidia/Nemotron-Math-Proofs-v1"""
    # Combine text columns
    parts = []
    if example.get('problem'):
        parts.append(f'Problem: {example["problem"]}')
    if example.get('formal_statement'):
        parts.append(f'Formal_Statement: {example["formal_statement"]}')
    if example.get('lean_header'):
        parts.append(f'Lean_Header: {example["lean_header"]}')
    if example.get('messages'):
        parts.append(f'Messages: {example["messages"]}')
    return '\n'.join(parts)


def extract_text_nvidia_nemotron_3_nano_rl_training_blend(example):
    """Extract embeddable text from nvidia/Nemotron-3-Nano-RL-Training-Blend"""
    # Combine text columns
    parts = []
    if example.get('responses_create_params'):
        parts.append(f'Responses_Create_Params: {example["responses_create_params"]}')
    if example.get('dataset'):
        parts.append(f'Dataset: {example["dataset"]}')
    return '\n'.join(parts)


def extract_text_nvidia_nemotron_agentic_v1(example):
    """Extract embeddable text from nvidia/Nemotron-Agentic-v1"""
    # Conversational format - concatenate messages
    messages = example['messages']
    text_parts = []
    for msg in messages:
        role = msg.get('role', 'unknown')
        content = msg.get('content', '')
        # Include reasoning_content if available
        if 'reasoning_content' in msg and msg['reasoning_content']:
            content = msg['reasoning_content'] + '\n' + content
        text_parts.append(f'{role}: {content}')
    return '\n'.join(text_parts)


def extract_text_nvidia_nemotron_competitive_programming_v1(example):
    """Extract embeddable text from nvidia/Nemotron-Competitive-Programming-v1"""
    # Conversational format - concatenate messages
    messages = example['messages']
    text_parts = []
    for msg in messages:
        role = msg.get('role', 'unknown')
        content = msg.get('content', '')
        # Include reasoning_content if available
        if 'reasoning_content' in msg and msg['reasoning_content']:
            content = msg['reasoning_content'] + '\n' + content
        text_parts.append(f'{role}: {content}')
    return '\n'.join(text_parts)


def extract_text_nvidia_nemotron_math_v2(example):
    """Extract embeddable text from nvidia/Nemotron-Math-v2"""
    # Conversational format - concatenate messages
    messages = example['messages']
    text_parts = []
    for msg in messages:
        role = msg.get('role', 'unknown')
        content = msg.get('content', '')
        # Include reasoning_content if available
        if 'reasoning_content' in msg and msg['reasoning_content']:
            content = msg['reasoning_content'] + '\n' + content
        text_parts.append(f'{role}: {content}')
    return '\n'.join(text_parts)


def extract_text_nvidia_nemotron_swe_v1(example):
    """Extract embeddable text from nvidia/Nemotron-SWE-v1"""
    # Conversational format - concatenate messages
    messages = example['messages']
    text_parts = []
    for msg in messages:
        role = msg.get('role', 'unknown')
        content = msg.get('content', '')
        text_parts.append(f'{role}: {content}')
    return '\n'.join(text_parts)

